/*
-- Query: SELECT * FROM estadisticas_futbol_2023.datos_equipos
-- Date: 2023-11-27 11:45
*/
use estadisticas_futbol_2023;
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Tigre','Tigre','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Belgrano de Cordoba','Belgrano','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Union de Santa Fe','Union Santa Fe','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Club Atletico Velez Sarsfield','Velez Sarsfield','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Talleres de Cordoba','Talleres Cordoba','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CSD Defensa y Justicia','Defensa y Justicia','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Independiente','Independiente','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Lanus','Lanus','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Boca Juniors','Boca Juniors','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Banfield','Banfield','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Colon de Santa Fe','Colon','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Gimnasia y Esgrima La Plata','Gimnasia La Plata','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Estudiantes de La Plata','Estudiantes','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Rosario Central','Rosario Central','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA San Lorenzo de Almagro','San Lorenzo','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Newell\'s Old Boys','Newell\'s Old Boys','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Arsenal de Sarandi','Arsenal de Sarandi','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Racing Club de Avellaneda','Racing Club','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA River Plate','River Plate','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Tucuman','Atletico Tucuman','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Godoy Cruz Antonio Tomba','Godoy Cruz','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Huracan','Huracan','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Argentinos Juniors','Argentinos Juniors','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Central Cordoba de Santiago del Estero','Central Cordoba SdE','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Platense','Platense','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Barracas Central','Barracas Central','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Sarmiento','Sarmiento','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Instituto AC Cordoba','Instituto','Argentina');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Ferroviaria Futebol','Ferroviaria','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Sport Club Corinthians Paulista','Corinthians','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Clube de Regatas do Flamengo Women','Flamengo W','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('SE Kindermann','Kindermann','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Santos FC','Santos','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Gremio FB Porto Alegrense Women','Gremio W','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Sao Paulo Futebol Clube Women','Sao Paulo Women','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('SE Palmeiras Women','Palmeiras Women','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Internacional RS','Internacional RS','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Cruzeiro EC Women','Cruzeiro W','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Bahia Women','Bahia W','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Real BrasiÂ­lia FC','Real BrasiÂ­lia W','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Mineiro Women','Atletico Mineiro W','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Club Athletico Paranaense','Athletico Paranaense','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Cear SC Women','Cear W','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Real Desportivo Ariquemes FC Women','Real Ariquemes W','Brazil');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Arsenal FC','Arsenal','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Tottenham Hotspur FC','Tottenham Hotspur','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Manchester City FC','Manchester City','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Crystal Palace FC','Crystal Palace','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Everton FC','Everton','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Burnley FC','Burnley','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('AFC Bournemouth','AFC Bournemouth','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Manchester United FC','Manchester United','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Liverpool FC','Liverpool','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Chelsea FC','Chelsea','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('West Ham United FC','West Ham United','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Newcastle United FC','Newcastle United','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Aston Villa FC','Aston Villa','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Fulham FC','Fulham','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Brighton & Hove Albion FC','Brighton & Hove Albion','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Nottingham Forest FC','Nottingham Forest','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Brentford FC','Brentford','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Wolverhampton Wanderers FC','Wolverhampton Wanderers','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Sheffield United FC','Sheffield United','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Luton Town FC','Luton Town','England');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('SSC Napoli','Napoli','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Juventus FC','Juventus','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('AS Roma','Roma','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Cagliari Calcio','Cagliari','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Torino FC','Torino','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Empoli FC','Empoli','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Genoa CFC','Genoa','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('AC Milan','AC Milan','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('SS Lazio','Lazio','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Atalanta Bergamasca Calcio','Atalanta','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Udinese Calcio','Udinese','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Bologna FC 1909','Bologna','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('US Sassuolo Calcio','Sassuolo','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('FC Internazionale Milano','Inter Milan','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('ACF Fiorentina','Fiorentina','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Hellas Verona FC','Hellas Verona','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Frosinone Calcio','Frosinone','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('US Salernitana 1919','Salernitana','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('US Lecce','Lecce','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('SS Monza 1912','Monza','Italy');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Villarreal CF','Villarreal','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('FC Barcelona','FC Barcelona','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Real Madrid CF','Real Madrid','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Sevilla FC','Sevilla FC','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Club Atletico de Madrid','Atletico Madrid','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('UD Las Palmas','UD Las Palmas','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Deportivo Alaves','Deportivo Alaves','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Real Club Celta de Vigo','Celta de Vigo','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Granada CF','Granada CF','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Real Betis Balompie','Real Betis','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Athletic Club Bilbao','Athletic Club Bilbao','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('CA Osasuna','CA Osasuna','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Valencia CF','Valencia CF','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Real Sociedad de Futbol','Real Sociedad','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Rayo Vallecano','Rayo Vallecano','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Getafe Club de Futbol','Getafe CF','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('UD AlmeriÂ­a','Almeria','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Real Club Deportivo Mallorca','RCD Mallorca','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Cadiz CF','Cadiz','Spain');
INSERT INTO `datos_equipos` (`team_name`,`common_name`,`country`) VALUES ('Girona FC','Girona FC','Spain');
