/*
-- Query: SELECT * FROM estadisticas_futbol_2023.paises
-- Date: 2023-11-27 11:47
*/
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Tigre');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Belgrano de Cordoba');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Union de Santa Fe');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Club Atletico Velez Sarsfield');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Talleres de Cordoba');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CSD Defensa y Justicia');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Independiente');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Lanus');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Boca Juniors');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Banfield');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Colon de Santa Fe');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Gimnasia y Esgrima La Plata');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Estudiantes de La Plata');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Rosario Central');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA San Lorenzo de Almagro');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Newell\'s Old Boys');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Arsenal de Sarandi');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Racing Club de Avellaneda');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA River Plate');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Tucuman');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Godoy Cruz Antonio Tomba');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Huracan');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Argentinos Juniors');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Central Cordoba de Santiago del Estero');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Platense');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Barracas Central');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','CA Sarmiento');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Argentina','Instituto AC Cordoba');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Ferroviaria Futebol');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Sport Club Corinthians Paulista');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Clube de Regatas do Flamengo Women');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','SE Kindermann');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Santos FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Gremio FB Porto Alegrense Women');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Sao Paulo Futebol Clube Women');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','SE Palmeiras Women');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Internacional RS');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Cruzeiro EC Women');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Bahia Women');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Real Brasi­lia FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','CA Mineiro Women');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Club Athletico Paranaense');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Cear SC Women');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Brazil','Real Desportivo Ariquemes FC Women');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Arsenal FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Tottenham Hotspur FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Manchester City FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Crystal Palace FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Everton FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Burnley FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','AFC Bournemouth');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Manchester United FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Liverpool FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Chelsea FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','West Ham United FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Newcastle United FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Aston Villa FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Fulham FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Brighton & Hove Albion FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Nottingham Forest FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Brentford FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Wolverhampton Wanderers FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Sheffield United FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('England','Luton Town FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','SSC Napoli');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Juventus FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','AS Roma');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Cagliari Calcio');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Torino FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Empoli FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Genoa CFC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','AC Milan');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','SS Lazio');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Atalanta Bergamasca Calcio');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Udinese Calcio');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Bologna FC 1909');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','US Sassuolo Calcio');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','FC Internazionale Milano');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','ACF Fiorentina');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Hellas Verona FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','Frosinone Calcio');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','US Salernitana 1919');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','US Lecce');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Italy','SS Monza 1912');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Villarreal CF');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','FC Barcelona');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Real Madrid CF');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Sevilla FC');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Club Atletico de Madrid');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','UD Las Palmas');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Deportivo Alaves');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Real Club Celta de Vigo');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Granada CF');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Real Betis Balompie');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Athletic Club Bilbao');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','CA Osasuna');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Valencia CF');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Real Sociedad de Futbol');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Rayo Vallecano');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Getafe Club de Futbol');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','UD Almeri­a');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Real Club Deportivo Mallorca');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Cadiz CF');
INSERT INTO `paises` (`country_name`,`team_name`) VALUES ('Spain','Girona FC');
