/*
-- Query: SELECT * FROM estadisticas_futbol_2023.referee
-- Date: 2023-11-27 11:48
*/
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Maximiliano','Ramirez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','German','Delfino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','SebastiÃ¡n','NicolÃ¡s Martinez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','German','Delfino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','German','Delfino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','SebastiÃ¡n','NicolÃ¡s Martinez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','German','Delfino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Franco','Acita');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Rodrigo','Hector Rivero');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','SebastiÃ¡n','NicolÃ¡s Martinez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','Nelson Sosa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Diego','Ceballos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Alejandro','Ramirez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','SebastiÃ¡n','NicolÃ¡s Martinez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','SebastiÃ¡n','NicolÃ¡s Martinez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','SebastiÃ¡n','NicolÃ¡s Martinez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','SebastiÃ¡n','NicolÃ¡s Martinez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','German','Delfino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Franco','Acita');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Facundo','Tello Figueroa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Sebastian','Zunino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nicolas','Lamolina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Dario','Herrera');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Hernan','Mastrangelo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Franco','Acita');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Silvio','Trucco');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Ariel','Penel');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Nazareno','Arasa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Leandro','Rey Hilfer');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Luis','Lobo Medina');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Rapallini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Echenique');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Echavarria');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Andres','Merlos');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Carlos','Gariano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','German','Delfino');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','SebastiÃ¡n','NicolÃ¡s Martinez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Yael','Falcon Perez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Fernando','Espinoza');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Pablo','Davalo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','Jorge','BaliÃ±o');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Argentina','SebastiÃ¡n','NicolÃ¡s Martinez');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Luca','Massimi');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Matteo','Marcenaro');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Giovanni','Ayroldi');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Andrea','Colombo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Ermanno','Feliciani');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Matteo','Marchetti');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Federico','Dionisi');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Antonio','Rapuano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Francesco','Cosso');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Luca','Pairetto');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Juan','Luca Sacchi');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Gianluca','Aureliano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Daniele','Doveri');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Maurizio','Mariani');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','noname','');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Marco','Di Bello');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Livio','Marinelli');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Antonio','Giua');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Davide','Massa');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Michael','Fabbri');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Marco','Piccinini');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Antonio','Rapuano');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Daniele','Orsato');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Marco','Guida');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Matteo','Marcenaro');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Andrea','Colombo');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Matteo','Marchetti');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Daniele','Chiffi');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Giovanni','Ayroldi');
INSERT INTO `referee` (`country_name`,`referee_name`,`referee_last_name`) VALUES ('Italy','Luca','Massimi');