/*
-- Query: SELECT * FROM estadisticas_futbol_2023.paises
-- Date: 2023-11-27 11:47
*/
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (1,'Argentina','CA Tigre');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (2,'Argentina','CA Belgrano de Cordoba');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (3,'Argentina','CA Union de Santa Fe');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (4,'Argentina','Club Atletico Velez Sarsfield');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (5,'Argentina','CA Talleres de Cordoba');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (6,'Argentina','CSD Defensa y Justicia');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (7,'Argentina','CA Independiente');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (8,'Argentina','CA Lanus');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (9,'Argentina','CA Boca Juniors');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (10,'Argentina','CA Banfield');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (11,'Argentina','Colon de Santa Fe');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (12,'Argentina','Gimnasia y Esgrima La Plata');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (13,'Argentina','Estudiantes de La Plata');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (14,'Argentina','CA Rosario Central');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (15,'Argentina','CA San Lorenzo de Almagro');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (16,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (17,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (18,'Argentina','Racing Club de Avellaneda');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (19,'Argentina','CA River Plate');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (20,'Argentina','CA Tucuman');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (21,'Argentina','Godoy Cruz Antonio Tomba');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (22,'Argentina','CA Huracan');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (23,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (24,'Argentina','CA Central Cordoba de Santiago del Estero');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (25,'Argentina','CA Platense');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (26,'Argentina','CA Barracas Central');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (27,'Argentina','CA Sarmiento');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (28,'Argentina','Instituto AC Cordoba');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (29,'Brazil','Ferroviaria Futebol');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (30,'Brazil','Sport Club Corinthians Paulista');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (31,'Brazil','Clube de Regatas do Flamengo Women');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (32,'Brazil','SE Kindermann');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (33,'Brazil','Santos FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (34,'Brazil','Gremio FB Porto Alegrense Women');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (35,'Brazil','Sao Paulo Futebol Clube Women');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (36,'Brazil','SE Palmeiras Women');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (37,'Brazil','Internacional RS');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (38,'Brazil','Cruzeiro EC Women');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (39,'Brazil','Bahia Women');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (40,'Brazil','Real Brasi­lia FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (41,'Brazil','CA Mineiro Women');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (42,'Brazil','Club Athletico Paranaense');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (43,'Brazil','Cear SC Women');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (44,'Brazil','Real Desportivo Ariquemes FC Women');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (45,'England','Arsenal FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (46,'England','Tottenham Hotspur FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (47,'England','Manchester City FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (48,'England','Crystal Palace FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (49,'England','Everton FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (50,'England','Burnley FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (51,'England','AFC Bournemouth');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (52,'England','Manchester United FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (53,'England','Liverpool FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (54,'England','Chelsea FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (55,'England','West Ham United FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (56,'England','Newcastle United FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (57,'England','Aston Villa FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (58,'England','Fulham FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (59,'England','Brighton & Hove Albion FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (60,'England','Nottingham Forest FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (61,'England','Brentford FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (62,'England','Wolverhampton Wanderers FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (63,'England','Sheffield United FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (64,'England','Luton Town FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (65,'Italy','SSC Napoli');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (66,'Italy','Juventus FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (67,'Italy','AS Roma');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (68,'Italy','Cagliari Calcio');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (69,'Italy','Torino FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (70,'Italy','Empoli FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (71,'Italy','Genoa CFC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (72,'Italy','AC Milan');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (73,'Italy','SS Lazio');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (74,'Italy','Atalanta Bergamasca Calcio');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (75,'Italy','Udinese Calcio');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (76,'Italy','Bologna FC 1909');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (77,'Italy','US Sassuolo Calcio');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (78,'Italy','FC Internazionale Milano');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (79,'Italy','ACF Fiorentina');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (80,'Italy','Hellas Verona FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (81,'Italy','Frosinone Calcio');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (82,'Italy','US Salernitana 1919');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (83,'Italy','US Lecce');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (84,'Italy','SS Monza 1912');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (85,'Spain','Villarreal CF');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (86,'Spain','FC Barcelona');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (87,'Spain','Real Madrid CF');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (88,'Spain','Sevilla FC');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (89,'Spain','Club Atletico de Madrid');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (90,'Spain','UD Las Palmas');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (91,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (92,'Spain','Real Club Celta de Vigo');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (93,'Spain','Granada CF');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (94,'Spain','Real Betis Balompie');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (95,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (96,'Spain','CA Osasuna');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (97,'Spain','Valencia CF');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (98,'Spain','Real Sociedad de Futbol');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (99,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (100,'Spain','Getafe Club de Futbol');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (101,'Spain','UD Almeri­a');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (102,'Spain','Real Club Deportivo Mallorca');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (103,'Spain','Cadiz CF');
INSERT INTO `` (`id_pais`,`country_name`,`team_name`) VALUES (104,'Spain','Girona FC');
