/*
-- Query: SELECT * FROM estadisticas_futbol_2023.tabla_de_asistidores
-- Date: 2023-11-13 11:15
*/
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1,'Adriian Sporle',1,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2,'Bruno Alejandro Pitton',1,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (3,'Brian Lautaro Guzmi',2,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (4,'Brian Nicola Aguirre',2,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (7,'Adriian Sporle',1,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (16,'Agustin Ismael Alvarez',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (34,'Agustin Ismael Alvarez',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (47,'Alan Rodriguez',1,'Uruguay','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (51,'Alejandro Gabriel Medina',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (65,'Alexis Martin Arias',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (69,'Alfredo Ramon Amarilla',0,'Paraguay','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (82,'Armando Jesus Mendez Alcorta',0,'Uruguay','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (86,'Augusto Schott',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (97,'Brandon Sosa',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (109,'Carlos Alberto OrdoÃ±ez Esterilla',0,'Colombia','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (118,'Christian Chimino',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (140,'David Sotelo',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (172,'Emiliano Sebastii Viveros Mereles',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (196,'Fabrizio Sartori Prieto',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (203,'Facundo Omar Cardozo',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (215,'Federico Lanzillotta',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (218,'Felipe San Juan',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (225,'Flabii LondoÃ±o Bedoya',2,'Colombia','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (237,'Franco Agustin Vega',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (248,'Franco Sergio Martinez',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (261,'Gaston Veron',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (262,'Genaro Ariel Rossi',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (275,'Gonzalo Emanuel Muscia',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (292,'Guillermo Balzi',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (295,'Guillermo Luis Ortiz',1,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (307,'Ignacio Gariglio',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (315,'Ivi Cabrera',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (316,'Ivan Glavinovich',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (331,'Jeronimo Russo',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (333,'Jherson Steven Mosquera Castro',2,'Colombia','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (343,'Joaquin Silvio Messi',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (352,'Jonathan Diego Menendez',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (353,'Jonathan Raccio',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (364,'Jose Maria Herrera',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (376,'Juan Cuesta',0,'Colombia','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (380,'Juan Ignacio Cavallaro',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (382,'Juan Ignacio Peinipil',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (383,'Juan Jose Cardozo',0,'Paraguay','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (397,'Julii Contrera',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (412,'Kevin Mac Allister',4,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (423,'Lautaro Nahuel Ovando',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (436,'Leandro Raul Moreira',1,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (439,'Leonardo Marchi Rivero',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (443,'Leonel Ezequiel Vangioni',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (444,'Leonel Gonzalez',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (450,'Lisandro Sebastii Montenegro',1,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (453,'Lucas Adrii Hoyos',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (476,'Luciano Sichez',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (482,'Luis Leal dos Anjos',3,'Puerto Principe','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (493,'Manuel Lopez',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (497,'Marcelo Cesar Esponda',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (506,'Mariano Bittolo',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (513,'Martin Luciano',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (538,'Matias Vera',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (544,'Mauro Antonio Burruchaga',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (547,'Maximiliano Centurion',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (554,'Miguel Angel Acosta',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (558,'Misael Jaime',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (567,'Nazareno Manuel Funez',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (603,'Pablo Javier Perez',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (605,'Pablo Minissale',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (640,'Romi Daniel Riquelme',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (642,'Romi Gabriel Vega',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (677,'Thiago Nuss',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (685,'Tobias Zarate',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (694,'Toma Berardozzi',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (702,'Toma Jacob',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (708,'Toma Perez',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (709,'Toma Sives',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (710,'Toma Sultani',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (722,'Victor Gustavo Velazquez Ramos',3,'Paraguay','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (724,'Willer Emilio Ditta Perez',0,'Colombia','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (725,'Williams Barlasina',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (731,'Zahir Facundo Mansilla',1,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1291,'Adam Smith',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1364,'Chris Mepham',0,'Wales','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1383,'David Brooks',1,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1427,'Gavin Kilkenny',0,'Republic of Ireland','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1433,'Hamed Traore',0,'Ivory Coast','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1448,'Illia Zabarnyi',0,'Ukraine','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1449,'Ionue Andrei Radu',0,'Romania','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1459,'Jaidon Anthony',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1464,'James Hill',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1489,'Joe Rothwell',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1507,'Justin Kluivert',0,'Netherlands','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1516,'Kieffer Moore',0,'Wales','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1524,'Lewis Cook',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1530,'Lloyd Kelly',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1565,'Maximillian James Aarons',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1573,'Milos Kerkez',0,'Hungary','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1588,'Neto',0,'Brazil','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1606,'Philip Billing',0,'Denmark','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1627,'Ryan Christie',0,'Scotland','AFC Bournemouth');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1688,'Aaron Escandell Banacloche',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1689,'Abdelkabir Abqar',0,'Morocco','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1690,'Abderrahman Rebbach',0,'Algeria','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1692,'Abdul Mumin',0,'Ghana','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1698,'AdriAn Lopez Garrote',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1699,'Adrian Rodriguez Gimenez',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1701,'Aimar Oroz',1,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1703,'Aitor FernAndez',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1705,'Aitor Paredes',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1707,'Alberto Perea',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1709,'Aleix Garcia',1,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1710,'Alejandro Balde',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1711,'Alejandro Catena',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1713,'Aleksandar Sedlar',0,'Serbia','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1718,'Alex Ujia Piriz',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1720,'Alfonso Espino',0,'Uruguay','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1730,'Ander Astralaga',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1732,'Ander Guevara',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1733,'Ander Herrera',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1734,'Ander SAnchez FernAndez De Lar',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1735,'Andoni Gorosabel',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1736,'AndresFilipe Magalhaes Ribeiro Ferreira',0,'Portugal','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1737,'Andreas Christensen',0,'Denmark','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1738,'Andrei Florin Ratiu',0,'Romania','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1741,'Ansu Fati',0,'Guinea-Bissau','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1744,'Antonio Blanco',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1749,'Antonio Sivera SilvA',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1750,'Aridane HernAndez Umpiarrez',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1754,'Artem Dovbyk',1,'Ukraine','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1756,'Asier Villalibre',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1761,'Berat Prados Diaz',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1763,'Benito Ramirez del Toro',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1764,'Bernardo Espinosa',0,'Colombia','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1769,'Bryan Zaragoza Martiez',2,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1777,'Carlos Nahuel Benavidez Protesoni',0,'Uruguay','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1778,'Carlos Neva Tey',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1779,'Cenk Abakcar',0,'Turkey','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1781,'Cesar Torrega Requeni',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1783,'Chimy Avila',1,'Argentina','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1785,'Cristhian Mosquera',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1786,'Cristhian Stuani',2,'Uruguay','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1787,'Cristian Ignacio Herrera Perez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1788,'Cristian Portugues',1,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1789,'Cristian Rivero',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1791,'Daley Blind',0,'Netherlands','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1792,'Daley Sinkgraven',0,'Netherlands','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1794,'Dani Garcia',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1798,'Dani Vivian',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1800,'Daniel Cardenas Lindez',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1803,'David Garcia',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1805,'David Lopez',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1808,'Diego Kochen',0,'USA','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1809,'Diego Lopez',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1811,'Diego Mendez',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1814,'Dimitri Foulquier',0,'France','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1815,'Dimitrios Stamatakis',0,'Greece','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1818,'Djibril Sow',0,'Switzerland','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1819,'Dodi Lukebakio',0,'Belgium','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1825,'Enzo Loiodice',0,'France','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1826,'Aric Curbelo de la Fe',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1827,'Eric Garcia',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1828,'Erik Lamela',1,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1831,'Famara Diedhiou',0,'Senegal','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1832,'Federico Gattoni',0,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1835,'Fermi Lopez Marti',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1836,'Fernando Francisco Reges',0,'Brazil','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1838,'FerrAn Torres',2,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1840,'Florian Lejeune',0,'France','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1843,'Fran Perez',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1846,'Francisco Jesus Crespo Garcia',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1848,'Frenkie de Jong',1,'Netherlands','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1850,'Gabriel Paulista',0,'Brazil','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1851,'Gaizka Garcia VAzquez',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1853,'Gavi',1,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1856,'Giorgi Gagua',0,'Georgia','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1857,'Giorgi Mamardashvili',0,'Georgia','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1861,'Gonzalo Montiel',0,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1862,'Gorka Guruzeta',2,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1869,'Hugo GonzAlez Sotos',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1870,'Hugo Guillamin',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1872,'ianis Hagi',0,'Romania','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1873,'Ibrahima Kebe',0,'Mali','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1876,'Ignasi Miquel i Pons',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1878,'Iker Almena Horcajo',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1879,'Iker Muniain',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1880,'Iker MuÃ±oz',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1883,'Imanol Garcia de Alboniz Crecente',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1884,'IÃ±aki GonzAlez Zambrano',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1885,'IÃ±aki Peza',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1886,'ligo Lekue',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1887,'IÃ±igo Martiez',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1888,'ligo Ruiz de Galarreta',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1891,'Isi Palazin',1,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1893,'IvAn Balliu',0,'Albania','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1895,'IvAn Marti',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1896,'Ivan Rakitic',0,'Croatia','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1902,'Jaume Domenech',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1904,'Javi Martiez',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1905,'Javier Guerra',1,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1906,'Javier Lopez Carballo',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1907,'Javier Martin Ansi',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1908,'Javier MuÃ±oz Jimenez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1910,'Jesus Corona',0,'Mexico','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1911,'Jesus LAzaro Owono Ngua Akeng',0,'Equatorial Guinea','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1912,'Jesus Navas',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1913,'Jesus Vallejo',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1914,'Jesus VAzquez',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1915,'Jhon Sola',0,'Colombia','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1916,'Joan JordAn',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1917,'Joao Cancelo',0,'Portugal','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1918,'Joao Felix',0,'Portugal','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1919,'Johan Mojica',0,'Colombia','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1921,'Jon Karrikaburu',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1922,'Jon Moncayola',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1925,'Jonathan Viera',1,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1928,'Jorge De Frutos SebastiAn',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1929,'Jorge Herrando',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1931,'Jorge Moreno San Vidal',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1933,'Jose Alejandro SuArez SuArez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1935,'Jose Angel Pozo',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1937,'Jose David Alvarez Adsuar',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1938,'Jose Gayo',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1939,'Jose Luis Garcia VayA',1,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1941,'Jose Manuel Arnaiz Diaz',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1947,'Juan Carlos Marti Corral',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1948,'Juan Cruz',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1951,'Juan Herzog',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1953,'Juan Luis SAnchez Velasco',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1955,'Juan Pedro Ramirez Lopez',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1957,'Julen Agirrezabala',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1958,'Jules Kounde',1,'France','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1959,'Julian Araujo',0,'Mexico','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1965,'Kike Barja',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1966,'Kike Garcia',2,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1967,'Kike Perez',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1968,'Kike Salas',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1970,'Kirian RodrAiguez Concepcion',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1973,'Loe  Bade',0,'France','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1975,'Lucas Boye',1,'Argentina','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1978,'Lucas Torre',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1984,'Malcom Adu Ares',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1985,'Mamadou Selu Diallo Diallo',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1986,'Mamadou Sylla Diallo',0,'Senegal','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1987,'Manu Bueno',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1990,'Manu Vallejo',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1992,'Marc Cardona Rovira',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1993,'Marc Casade',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1996,'Marc-Andre ter Stegen',0,'Germany','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1997,'Marcos AcuÃ±a',0,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1998,'Marcos Alonso',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2000,'Mario Dominguez',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2001,'Mario GonzAlez Bravo',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2003,'Marko Dmitrovic',0,'Serbia','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2005,'Marti Pascual Castillo',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2006,'Marti Tejen Fauli',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2009,'Matia Airbol',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2014,'MAximo Perrone',0,'Argentina','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2016,'Miguel Angel Morro',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2017,'Miguel Angel Rubio Lestan',1,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2018,'Miguel De La Fuente Escudero',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2020,'Mika MArmol Medina',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2022,'Mikel Vesga',2,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2025,'Moi Gomez',1,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2027,'Mouctar Diakhaby',1,'France','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2028,'Munir El Haddadi',0,'Morocco','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2029,'Myrto Uzuni',1,'Albania','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2031,'Nacho Vidal',1,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2033,'Nahuel Tenaglia',0,'Argentina','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2034,'Nemanja Gudelj',1,'Serbia','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2037,'Nikola Marae',0,'Serbia','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2038,'Njego Petrovic',0,'Serbia','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2039,'Oihan Sancet',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2040,'Aliver Torres',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2043,'Omenuke MFulu',0,'Congo DR','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2044,'Oriol Romeu',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2045,'Ascar de Marcos',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2046,'Ascar Melendo Jimenez',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2048,'Ascar Trejo',0,'Argentina','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2049,'Ascar Valenti',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2051,'Pablo Gozalbez Gilabert',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2052,'Pablo IbÃ±ez',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2055,'Pablo MuÃ±oz',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2056,'Pablo Torre',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2057,'Pablo Valencia',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2058,'Papu Gomez',0,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2059,'Pathe  Ciss',1,'Senegal','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2060,'Pau Cubarsao Paredes',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2062,'Paulo Gazzaniga',0,'Argentina','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2063,'Pedri',1,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2064,'Pep Chavarria',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2067,'Peru Nolaskoain',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2069,'Radamel Falcao',0,'Colombia','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2070,'Rafa Mir',1,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2072,'Rafael Mari Zamora',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2074,'Randy Ntekja',1,'France','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2075,'Raphinha',0,'Brazil','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2077,'Raul FernAndez',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2079,'Raul Garcia',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2080,'Raul Garcia de Haro',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2082,'Ricard SAnchez Sendra',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2089,'Roman Yaremchuk',0,'Ukraine','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2090,'Ronald Araujo',0,'Uruguay','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2092,'Ruben Duarte',1,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2093,'Ruben Garcia',1,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2094,'Ruben Iranzo',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2095,'Ruben PeÃ±a',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2099,'Salvador SAnchez Ponce',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2102,'Sandro Ramirez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2105,'Santiago Bueno',0,'Uruguay','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2106,'Saul Basilio Coco-Bassey Oubiua',0,'Equatorial Guinea','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2107,'Selim Amallah',0,'Belgium','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2109,'Sergi Canos',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2110,'Sergi Cardona Bermudez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2111,'Sergi Roberto',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2114,'Sergio Camello',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2115,'Sergio Herrera',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2116,'Sergio Ruiz Alonso',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2118,'Silvi Clua Oya',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2119,'Sory Kaba',0,'Guinea','UD Las Palmas');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2123,'Stole Dimitrievski',0,'FYR Macedonia','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2124,'Thierry Correia',0,'Portugal','Valencia CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2126,'Tiago Manuel Dias Correia',0,'Cape Verde','Rayo Vallecano');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2127,'Toni Fuidias',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2129,'Unai Egueluz Arroyo',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2130,'Unai Garcia',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2131,'Unai Gomez Etxebarria',1,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2134,'Unai Simon',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2136,'Valery FernAndez',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2138,'Victor David Diaz Miguel',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2142,'Wilson ManafA',0,'Portugal','Granada CF');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2143,'Xeber Alkain Mitxelena',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2144,'Yangel Herrera',2,'Venezuela','Girona FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2145,'Yassine Bounou',0,'Morocco','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2147,'Youssef En-Nesyri',1,'Morocco','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2148,'Yuri Berchiche',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2149,'Arjan Nyland',0,'Norway','Sevilla FC');
INSERT INTO `` (`id_tab_asist`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2171,'Alessandro Florenzi',0,'Italy','AC Milan');
