/*
-- Query: SELECT * FROM estadisticas_futbol_2023.tabla_de_goleadores
-- Date: 2023-11-13 11:15
*/
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (7,'Adriian Sporle',1,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (16,'Agustin Ismael Alvarez',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (33,'Alan Rodriguez',1,'Uruguay','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (40,'Alejandro Gabriel Medina',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (55,'Alexis Martin Arias',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (61,'Alfredo Ramon Amarilla',0,'Paraguay','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (73,'Angelo Martino',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (80,'Armando Jesus Mendez Alcorta',0,'Uruguay','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (84,'Augusto Schott',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (103,'Braian Rivero',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (104,'Brandon Sosa',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (111,'Brian Lautaro Guzmi',2,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (113,'Brian Nicola Aguirre',2,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (115,'Bruno Alejandro Pitton',1,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (127,'Carlos Alberto OrdoÃ±ez Esterilla',0,'Colombia','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (137,'Christian Chimino',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (151,'Cristian Ferreira',3,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (165,'Daniel Lucero',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (175,'David Sotelo',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (216,'Emiliano Sebastii Viveros Mereles',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (249,'Fabricio Dominguez',0,'Uruguay','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (252,'Fabrizio Sartori Prieto',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (260,'Facundo Ferreyra',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (269,'Facundo Omar Cardozo',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (270,'Facundo Pons',2,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (285,'Federico Lanzillotta',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (287,'Federico Redondo',1,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (292,'Felipe San Juan',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (303,'Flabii LondoÃ±o Bedoya',2,'Colombia','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (310,'Francisco Gonzalez',1,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (311,'Francisco Gonzalez Metilli',5,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (320,'Franco Agustin Vega',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (329,'Franco Moyano',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (336,'Franco Sergio Martinez',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (347,'Gabriel Avalos',14,'Paraguay','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (366,'Gaston Veron',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (367,'Genaro Ariel Rossi',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (385,'Gonzalo Emanuel Muscia',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (404,'Guillermo Balzi',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (409,'Guillermo Luis Ortiz',1,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (425,'Ignacio Gariglio',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (430,'Ignacio Schor',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (437,'Ivi Cabrera',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (438,'Ivan Glavinovich',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (439,'Ivi Gomez',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (451,'Javier Cabrera',0,'Uruguay','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (460,'Jeremias Perez Tica',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (463,'Jeronimo Russo',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (465,'Jherson Steven Mosquera Castro',2,'Colombia','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (476,'Joaquin Silvio Messi',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (486,'Jonathan Diego Menendez',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (487,'Jonathan Galvi',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (488,'Jonathan Raccio',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (492,'Jorge Eduardo Recalde Ramirez',6,'Paraguay','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (504,'Jose Maria Herrera',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (520,'Juan Cuesta',0,'Colombia','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (526,'Juan Ignacio Cavallaro',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (531,'Juan Ignacio Peinipil',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (534,'Juan Jose Cardozo',0,'Paraguay','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (546,'Juan Sebastii Sforza',2,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (553,'Julii Contrera',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (570,'Kevin Mac Allister',4,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (583,'Lautaro Nahuel Ovando',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (600,'Leandro Raul Moreira',1,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (605,'Leonardo Heredia',4,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (606,'Leonardo Marchi Rivero',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (613,'Leonel Ezequiel Vangioni',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (614,'Leonel Gonzalez',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (620,'Lisandro Sebastii Montenegro',1,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (624,'Lucas Adrii Hoyos',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (633,'Lucas Brochero',1,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (654,'Lucas Villalba',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (658,'Luciano Emilio Gondou Zanelli',10,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (663,'Luciano Sichez',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (670,'Luis Leal dos Anjos',3,'Puerto Principe','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (683,'Manuel Lopez',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (689,'Marcelo Cesar Esponda',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (697,'Marco Di Cesare',1,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (702,'Marcos Portillo',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (703,'Mariano Bittolo',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (713,'Martin Luciano',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (752,'Matias Vera',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (758,'Mauro Antonio Burruchaga',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (766,'Maximiliano Centurion',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (776,'Miguel Angel Acosta',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (781,'Miguel Torren',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (786,'Misael Jaime',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (797,'Nazareno Manuel Funez',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (799,'Nestor Adriel Breitenbruch',1,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (846,'Pablo Javier Perez',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (848,'Pablo Minissale',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (869,'Ramiro Sordo',3,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (884,'Rodrigo Cabral',1,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (900,'Romi Daniel Riquelme',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (902,'Romi Gabriel Vega',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (912,'Santiago Federico Toloza',5,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (920,'Santiago Montiel',2,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (947,'Thiago Nuss',0,'Argentina','Argentinos Juniors');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (957,'Tobias Zarate',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (967,'Toma Berardozzi',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (976,'Toma Jacob',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (985,'Toma Perez',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (986,'Toma Sives',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (987,'Toma Sultani',0,'Argentina','Arsenal de Sarandi');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1002,'Victor Gustavo Velazquez Ramos',3,'Paraguay','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1007,'Willer Emilio Ditta Perez',0,'Colombia','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1008,'Williams Barlasina',0,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1014,'Zahir Facundo Mansilla',1,'Argentina','Newell\'s Old Boys');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1768,'Adam Smith',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1848,'Chris Mepham',0,'Wales','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1870,'David Brooks',1,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1884,'Dominic Solanke',2,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1919,'Gavin Kilkenny',0,'Republic of Ireland','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1925,'Hamed Traore',0,'Ivory Coast','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1942,'Illia Zabarnyi',0,'Ukraine','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1943,'Ionue Andrei Radu',0,'Romania','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1955,'Jaidon Anthony',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1960,'James Hill',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (1989,'Joe Rothwell',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2013,'Justin Kluivert',0,'Netherlands','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2023,'Kieffer Moore',0,'Wales','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2033,'Lewis Cook',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2039,'Lloyd Kelly',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2060,'Marcos Senesi',0,'Argentina','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2062,'Marcus Tavernier',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2082,'Maximillian James Aarons',0,'England','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2090,'Milos Kerkez',0,'Hungary','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2110,'Neto',0,'Brazil','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2136,'Philip Billing',0,'Denmark','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2159,'Ryan Christie',0,'Scotland','AFC Bournemouth');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2230,'Aaron Escandell Banacloche',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2231,'Abdelkabir Abqar',0,'Morocco','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2232,'Abderrahman Rebbach',0,'Algeria','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2234,'Abdul Mumin',0,'Ghana','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2240,'AdriAn Lopez Garrote',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2241,'Adrian Rodriguez Gimenez',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2244,'Aimar Oroz',1,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2246,'Aitor FernAndez',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2248,'Aitor Paredes',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2251,'Alberto Perea',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2253,'Aleix Garcia',1,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2254,'Alejandro Balde',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2255,'Alejandro Catena',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2257,'Aleksandar Sedlar',0,'Serbia','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2263,'Alex Ujia Piriz',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2265,'Alfonso Espino',0,'Uruguay','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2276,'Ander Astralaga',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2278,'Ander Guevara',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2279,'Ander Herrera',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2280,'Ander SAnchez FernAndez De Lar',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2281,'Andoni Gorosabel',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2282,'Andres Almeida',0,'Portugal','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2283,'AndresFilipe Magalhaes Ribeiro Ferreira',0,'Portugal','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2284,'Andreas Christensen',0,'Denmark','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2285,'Andrei Florin Ratiu',0,'Romania','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2289,'Ansu Fati',0,'Guinea-Bissau','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2290,'Ante Budimir',0,'Croatia','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2293,'Antonio Blanco',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2298,'Antonio Sivera SilvA',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2299,'Aridane HernAndez Umpiarrez',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2301,'Arnau Martinez',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2304,'Artem Dovbyk',1,'Ukraine','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2306,'Asier Villalibre',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2311,'Berat Prados Diaz',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2313,'Benito Ramirez del Toro',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2314,'Bernardo Espinosa',0,'Colombia','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2320,'Bryan Zaragoza Martiez',2,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2328,'Carlos Nahuel Benavidez Protesoni',0,'Uruguay','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2329,'Carlos Neva Tey',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2330,'Cenk Abakcar',0,'Turkey','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2332,'Cesar Torrega Requeni',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2334,'Chimy Avila',1,'Argentina','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2336,'Cristhian Mosquera',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2337,'Cristhian Stuani',2,'Uruguay','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2338,'Cristian Ignacio Herrera Perez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2339,'Cristian Portugues',1,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2340,'Cristian Rivero',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2342,'Daley Blind',0,'Netherlands','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2343,'Daley Sinkgraven',0,'Netherlands','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2345,'Dani Garcia',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2349,'Dani Vivian',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2351,'Daniel Cardenas Lindez',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2356,'David Garcia',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2358,'David Lopez',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2361,'Diego Kochen',0,'USA','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2362,'Diego Lopez',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2364,'Diego Mendez',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2367,'Dimitri Foulquier',0,'France','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2368,'Dimitrios Stamatakis',0,'Greece','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2371,'Djibril Sow',0,'Switzerland','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2372,'Dodi Lukebakio',0,'Belgium','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2378,'Enzo Loiodice',0,'France','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2379,'Aric Curbelo de la Fe',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2380,'Eric Garcia',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2381,'Erik Lamela',1,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2384,'Famara Diedhiou',0,'Senegal','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2385,'Federico Gattoni',0,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2388,'Fermi Lopez Marti',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2389,'Fernando Francisco Reges',0,'Brazil','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2391,'FerrAn Torres',2,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2393,'Florian Lejeune',0,'France','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2396,'Fran Perez',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2399,'Francisco Jesus Crespo Garcia',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2401,'Frenkie de Jong',1,'Netherlands','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2403,'Gabriel Paulista',0,'Brazil','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2404,'Gaizka Garcia VAzquez',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2406,'Gavi',1,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2407,'Gerard Gumbau',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2410,'Giorgi Gagua',0,'Georgia','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2411,'Giorgi Mamardashvili',0,'Georgia','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2417,'Gonzalo Montiel',0,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2418,'Gonzalo Villar',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2419,'Gorka Guruzeta',2,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2427,'Hugo Duro',1,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2428,'Hugo GonzAlez Sotos',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2429,'Hugo Guillamin',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2432,'ianis Hagi',0,'Romania','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2433,'Ibrahima Kebe',0,'Mali','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2436,'Ignasi Miquel i Pons',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2438,'Iker Almena Horcajo',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2439,'Iker Muniain',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2440,'Iker MuÃ±oz',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2443,'Alkay Gundogan',0,'Germany','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2444,'Imanol Garcia de Alboniz Crecente',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2445,'IÃ±aki GonzAlez Zambrano',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2446,'IÃ±aki Peza',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2447,'IÃ±aki Williams',1,'Ghana','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2448,'ligo Lekue',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2449,'IÃ±igo Martiez',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2450,'ligo Ruiz de Galarreta',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2453,'Isi Palazin',1,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2455,'IvAn Balliu',0,'Albania','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2457,'IvAn Marti',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2458,'Ivan Rakitic',0,'Croatia','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2464,'Jaume Domenech',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2467,'Javi Martiez',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2468,'Javier Guerra',1,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2469,'Javier Lopez Carballo',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2470,'Javier Martin Ansi',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2471,'Javier MuÃ±oz Jimenez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2473,'Jesus Areso Blanco',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2474,'Jesus Corona',0,'Mexico','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2475,'Jesus LAzaro Owono Ngua Akeng',0,'Equatorial Guinea','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2476,'Jesus Navas',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2477,'Jesus Vallejo',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2478,'Jesus VAzquez',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2479,'Jhon Sola',0,'Colombia','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2480,'Joan JordAn',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2481,'Joao Cancelo',0,'Portugal','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2482,'Joao Felix',0,'Portugal','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2483,'Johan Mojica',0,'Colombia','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2485,'Jon Guridi Aldalur',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2486,'Jon Karrikaburu',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2487,'Jon Moncayola',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2490,'Jonathan Viera',1,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2493,'Jorge De Frutos SebastiAn',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2494,'Jorge Herrando',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2496,'Jorge Moreno San Vidal',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2498,'Jose Alejandro SuArez SuArez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2500,'Jose Angel Pozo',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2502,'Jose Antonio Rodriguez Diaz',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2503,'Jose Callejon',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2504,'Jose David Alvarez Adsuar',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2505,'Jose Gayo',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2506,'Jose Luis Garcia VayA',1,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2508,'Jose Manuel Arnaiz Diaz',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2515,'Juan Carlos Marti Corral',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2516,'Juan Cruz',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2519,'Juan Herzog',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2521,'Juan Luis SAnchez Velasco',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2523,'Juan Pedro Ramirez Lopez',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2526,'Julen Agirrezabala',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2527,'Jules Kounde',1,'France','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2528,'Julian Araujo',0,'Mexico','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2534,'Kike Barja',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2535,'Kike Garcia',2,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2536,'Kike Perez',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2537,'Kike Salas',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2539,'Kirian RodrAiguez Concepcion',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2540,'Lamine Yamal',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2544,'Loe  Bade',0,'France','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2546,'Lucas Boye',1,'Argentina','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2548,'Lucas Ocampos',0,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2551,'Lucas Torre',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2554,'Luis Jesus Rioja GonzAlez',1,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2558,'Malcom Adu Ares',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2559,'Mamadou Selu Diallo Diallo',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2560,'Mamadou Sylla Diallo',0,'Senegal','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2561,'Manu Bueno',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2565,'Manu Vallejo',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2567,'Marc Cardona Rovira',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2568,'Marc Casade',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2571,'Marc-Andre ter Stegen',0,'Germany','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2572,'Marcos AcuÃ±a',0,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2573,'Marcos Alonso',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2575,'Mario Dominguez',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2576,'Mario GonzAlez Bravo',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2578,'Marko Dmitrovic',0,'Serbia','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2580,'Marti Pascual Castillo',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2581,'Marti Tejen Fauli',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2584,'Matia Airbol',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2589,'MAximo Perrone',0,'Argentina','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2591,'Miguel Angel Morro',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2592,'Miguel Angel Rubio Lestan',1,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2593,'Miguel De La Fuente Escudero',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2594,'Miguel Gutierrez',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2596,'Mika MArmol Medina',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2599,'Mikel Vesga',2,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2602,'Moi Gomez',1,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2604,'Mouctar Diakhaby',1,'France','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2605,'Munir El Haddadi',0,'Morocco','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2606,'Myrto Uzuni',1,'Albania','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2608,'Nacho Vidal',1,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2610,'Nahuel Tenaglia',0,'Argentina','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2611,'Nemanja Gudelj',1,'Serbia','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2614,'Nico Williams',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2615,'Nikola Marae',0,'Serbia','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2616,'Njego Petrovic',0,'Serbia','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2617,'Oihan Sancet',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2618,'Aliver Torres',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2621,'Omenuke MFulu',0,'Congo DR','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2622,'Oriol Romeu',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2623,'Ascar de Marcos',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2624,'Ascar Melendo Jimenez',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2626,'Ascar Trejo',0,'Argentina','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2627,'Ascar Valenti',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2629,'Pablo Gozalbez Gilabert',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2630,'Pablo IbÃ±ez',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2633,'Pablo MuÃ±oz',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2634,'Pablo Torre',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2635,'Pablo Valencia',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2636,'Papu Gomez',0,'Argentina','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2637,'Pathe  Ciss',1,'Senegal','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2638,'Pau Cubarsao Paredes',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2640,'Paulo Gazzaniga',0,'Argentina','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2641,'Pedri',1,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2642,'Pep Chavarria',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2645,'Peru Nolaskoain',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2647,'Radamel Falcao',0,'Colombia','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2648,'Rafa Mir',1,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2650,'Rafael Mari Zamora',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2652,'Randy Ntekja',1,'France','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2653,'Raphinha',0,'Brazil','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2655,'Raul de TomAs',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2656,'Raul FernAndez',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2658,'Raul Garcia',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2659,'Raul Garcia de Haro',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2661,'Ricard SAnchez Sendra',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2662,'Robert Lewandowski',2,'Poland','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2670,'Roman Yaremchuk',0,'Ukraine','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2671,'Ronald Araujo',0,'Uruguay','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2673,'Ruben Duarte',1,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2674,'Ruben Garcia',1,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2675,'Ruben Iranzo',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2676,'Ruben PeÃ±a',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2680,'Salvador SAnchez Ponce',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2683,'Sandro Ramirez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2686,'Santiago Bueno',0,'Uruguay','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2687,'Saul Basilio Coco-Bassey Oubiua',0,'Equatorial Guinea','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2689,'SAvio',0,'Brazil','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2690,'Selim Amallah',0,'Belgium','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2692,'Sergi Canos',0,'Spain','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2693,'Sergi Cardona Bermudez',0,'Spain','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2695,'Sergi Roberto',0,'Spain','FC Barcelona');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2698,'Sergio Camello',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2699,'Sergio Herrera',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2700,'Sergio Ruiz Alonso',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2702,'Silvi Clua Oya',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2703,'Sory Kaba',0,'Guinea','UD Las Palmas');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2707,'Stole Dimitrievski',0,'FYR Macedonia','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2708,'Suso',0,'Spain','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2710,'Thierry Correia',0,'Portugal','Valencia CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2712,'Tiago Manuel Dias Correia',0,'Cape Verde','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2713,'Toni Fuidias',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2717,'Unai Egueluz Arroyo',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2718,'Unai Garcia',0,'Spain','CA Osasuna');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2719,'Unai Gomez Etxebarria',1,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2720,'Unai Lopez',0,'Spain','Rayo Vallecano');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2723,'Unai Simon',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2725,'Valery FernAndez',0,'Spain','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2727,'Victor David Diaz Miguel',0,'Spain','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2728,'Viktor Tsygankov',0,'Ukraine','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2732,'Wilson ManafA',0,'Portugal','Granada CF');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2733,'Xeber Alkain Mitxelena',0,'Spain','Deportivo Alaves');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2734,'Yan Couto',0,'Brazil','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2735,'Yangel Herrera',2,'Venezuela','Girona FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2737,'Yassine Bounou',0,'Morocco','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2739,'Youssef En-Nesyri',1,'Morocco','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2741,'Yuri Berchiche',0,'Spain','Athletic Club Bilbao');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2742,'Arjan Nyland',0,'Norway','Sevilla FC');
INSERT INTO `` (`id_tab_gol`,`full_name`,`total_goles`,`country`,`equipo`) VALUES (2764,'Alessandro Florenzi',0,'Italy','AC Milan');
