/*
-- Query: SELECT * FROM estadisticas_futbol_2023.datos_equipos
-- Date: 2023-11-12 12:15
*/
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (1,'CA Tigre','Tigre','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (2,'CA Belgrano de Cordoba','Belgrano','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (3,'CA Union de Santa Fe','Union Santa Fe','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (4,'Club Atletico Velez Sarsfield','Velez Sarsfield','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (5,'CA Talleres de Cordoba','Talleres Cordoba','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (6,'CSD Defensa y Justicia','Defensa y Justicia','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (7,'CA Independiente','Independiente','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (8,'CA Lanus','Lanus','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (9,'CA Boca Juniors','Boca Juniors','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (10,'CA Banfield','Banfield','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (11,'Colon de Santa Fe','Colon','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (12,'Gimnasia y Esgrima La Plata','Gimnasia La Plata','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (13,'Estudiantes de La Plata','Estudiantes','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (14,'CA Rosario Central','Rosario Central','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (15,'CA San Lorenzo de Almagro','San Lorenzo','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (16,'Newell\'s Old Boys','Newell\'s Old Boys','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (17,'Arsenal de Sarandi','Arsenal de Sarandi','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (18,'Racing Club de Avellaneda','Racing Club','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (19,'CA River Plate','River Plate','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (20,'CA Tucuman','Atletico Tucuman','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (21,'Godoy Cruz Antonio Tomba','Godoy Cruz','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (22,'CA Huracan','Huracan','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (23,'Argentinos Juniors','Argentinos Juniors','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (24,'CA Central Cordoba de Santiago del Estero','Central Cordoba SdE','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (25,'CA Platense','Platense','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (26,'CA Barracas Central','Barracas Central','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (27,'CA Sarmiento','Sarmiento','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (28,'Instituto AC Cordoba','Instituto','Argentina');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (29,'Ferroviaria Futebol','Ferroviaria','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (30,'Sport Club Corinthians Paulista','Corinthians','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (31,'Clube de Regatas do Flamengo Women','Flamengo W','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (32,'SE Kindermann','Kindermann','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (33,'Santos FC','Santos','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (34,'Gremio FB Porto Alegrense Women','Gremio W','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (35,'Sao Paulo Futebol Clube Women','Sao Paulo Women','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (36,'SE Palmeiras Women','Palmeiras Women','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (37,'Internacional RS','Internacional RS','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (38,'Cruzeiro EC Women','Cruzeiro W','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (39,'Bahia Women','Bahia W','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (40,'Real Brasi­lia FC','Real Brasi­lia W','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (41,'CA Mineiro Women','Atletico Mineiro W','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (42,'Club Athletico Paranaense','Athletico Paranaense','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (43,'Cear SC Women','Cear W','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (44,'Real Desportivo Ariquemes FC Women','Real Ariquemes W','Brazil');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (45,'Arsenal FC','Arsenal','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (46,'Tottenham Hotspur FC','Tottenham Hotspur','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (47,'Manchester City FC','Manchester City','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (48,'Crystal Palace FC','Crystal Palace','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (49,'Everton FC','Everton','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (50,'Burnley FC','Burnley','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (51,'AFC Bournemouth','AFC Bournemouth','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (52,'Manchester United FC','Manchester United','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (53,'Liverpool FC','Liverpool','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (54,'Chelsea FC','Chelsea','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (55,'West Ham United FC','West Ham United','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (56,'Newcastle United FC','Newcastle United','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (57,'Aston Villa FC','Aston Villa','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (58,'Fulham FC','Fulham','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (59,'Brighton & Hove Albion FC','Brighton & Hove Albion','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (60,'Nottingham Forest FC','Nottingham Forest','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (61,'Brentford FC','Brentford','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (62,'Wolverhampton Wanderers FC','Wolverhampton Wanderers','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (63,'Sheffield United FC','Sheffield United','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (64,'Luton Town FC','Luton Town','England');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (65,'SSC Napoli','Napoli','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (66,'Juventus FC','Juventus','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (67,'AS Roma','Roma','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (68,'Cagliari Calcio','Cagliari','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (69,'Torino FC','Torino','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (70,'Empoli FC','Empoli','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (71,'Genoa CFC','Genoa','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (72,'AC Milan','AC Milan','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (73,'SS Lazio','Lazio','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (74,'Atalanta Bergamasca Calcio','Atalanta','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (75,'Udinese Calcio','Udinese','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (76,'Bologna FC 1909','Bologna','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (77,'US Sassuolo Calcio','Sassuolo','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (78,'FC Internazionale Milano','Inter Milan','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (79,'ACF Fiorentina','Fiorentina','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (80,'Hellas Verona FC','Hellas Verona','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (81,'Frosinone Calcio','Frosinone','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (82,'US Salernitana 1919','Salernitana','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (83,'US Lecce','Lecce','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (84,'SS Monza 1912','Monza','Italy');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (85,'Villarreal CF','Villarreal','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (86,'FC Barcelona','FC Barcelona','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (87,'Real Madrid CF','Real Madrid','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (88,'Sevilla FC','Sevilla FC','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (89,'Club Atletico de Madrid','Atletico Madrid','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (90,'UD Las Palmas','UD Las Palmas','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (91,'Deportivo Alaves','Deportivo Alaves','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (92,'Real Club Celta de Vigo','Celta de Vigo','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (93,'Granada CF','Granada CF','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (94,'Real Betis Balompie','Real Betis','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (95,'Athletic Club Bilbao','Athletic Club Bilbao','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (96,'CA Osasuna','CA Osasuna','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (97,'Valencia CF','Valencia CF','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (98,'Real Sociedad de Futbol','Real Sociedad','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (99,'Rayo Vallecano','Rayo Vallecano','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (100,'Getafe Club de Futbol','Getafe CF','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (101,'UD Almeri­a','Almeria','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (102,'Real Club Deportivo Mallorca','RCD Mallorca','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (103,'Cadiz CF','Cadiz','Spain');
INSERT INTO `` (`id_equipo`,`team_name`,`common_name`,`country`) VALUES (104,'Girona FC','Girona FC','Spain');
